### ISSUE TITLE
Link annotation to Manifest it comes from (within in IIIF 2)

### ISSUE THREAD

**Issue by glenrobson** [ProjectMirador/mirador-annotations#20]
Is there a way to add a link to the Manifest where the canvas that is being annotated lives? Canvas Ids are often not resolvable so to find the image you are annotating you need access to the Manifest. In Mirador2 this was handled here:

https://github.com/ProjectMirador/mirador/blob/32e6bd5897e36611afbf0a8986051eaecac15011/js/src/annotations/mirador21Strategy.js#L39

and here:

https://github.com/ProjectMirador/mirador/blob/32e6bd5897e36611afbf0a8986051eaecac15011/js/src/annotations/miradorDualStrategy.js#L54

but this doesn't seem possible in this plugin as you only have access to the canvas id. For the SimpleAnnotationServer ideally I would like access to the manifest ID and label. The label is for this issue:

https://github.com/glenrobson/SimpleAnnotationServer/issues/64

**Comment by glenrobson** [comment]
I think this would be `partof` in IIIF version 3.0:

https://iiif.io/api/presentation/3.0/#partof

**Comment by mejackreed** [comment]
@glenrobson would this need to be part of the annotationPage? https://www.w3.org/TR/annotation-model/#h-annotation-page

Or would we want to just use this to interact w/ SAS rather than part of the `WebAnnotation`

**Comment by glenrobson** [comment]
I don't think it would do any harm to be in an annotationPage but it is SAS specific so fine if its available in the adapter and not part of `WebAnnotation`. I believe an annotationPage can contain annotations from multiple canvases and manifests so in some ways having it would be useful but generally when you are working with annotationPages you start from the manifest so don't need to go the other way. 

I think the annotation with the link to the manifest would look like:

```
{
  "@context": [
    "http://www.w3.org/ns/anno.jsonld",
    "http://iiif.io/api/presentation/3/context.json"
  ],
  "id": "http://example.org/anno1",
  "type": "Annotation",
  "motivation": "supplementing", 
  "body": {
        language: 'en',
        type: 'TextualBody',
        value: "annotation",
  },
  "target": {
    "id": "http://example.org/manifest/1/canvas/1",
    "type": "Canvas",
    "selector": {
       "type": "FragmentSelector",
       "conformsTo": "http://www.w3.org/TR/media-frags/",
       "value": "xywh=10,10,100,100"
     }
    "partOf": [
          {
                "id": ""http://example.org/manifest/1.json",
                "type": "Manifest",
                "label": { "en": [ "Manifest title" ] } }
          }
    ]
  }
}
```

I think because I'm asserting the target is a `canvas` it would need the selector to say which part of the canvas the annotation is relevant to.

**Comment by glenrobson** [comment]
For info there are some useful W3C annotations here: https://github.com/dlcs/elucidate-server/tree/master/elucidate-server/src/test/resources/example-w3c-annotation

**Comment by robcast** [comment]
I like the idea of having the reference to the containing manifest for all annotations.

It makes the target slightly more complex but targets have to be more complex anyway...

**Comment by mejackreed** [comment]
@glenrobson have you seen any examples with multiple selectors?

**Comment by glenrobson** [comment]
I haven't seen one no. I think reading the spec if would look like this (assuming your thinking of the SVG one):

```
{
  "@context": [
    "http://www.w3.org/ns/anno.jsonld",
    "http://iiif.io/api/presentation/3/context.json"
  ],
  "id": "http://example.org/anno1",
  "type": "Annotation",
  "motivation": "supplementing", 
  "body": {
        language: 'en',
        type: 'TextualBody',
        value: "annotation",
  },
  "target": {
    "type": "SpecificResource",
    "source": {
          "id": "http://example.org/manifest/1/canvas/1",
          "type": "Canvas",
          "label": { "en": [ "Page 1" ] } },
          "partOf": [
             {
                   "id": ""http://example.org/manifest/1.json",
                   "type": "Manifest",
                   "label": { "en": [ "Manifest title" ] } }
             }
          ]
    }
    "selector": [{
       "type": "FragmentSelector",
       "conformsTo": "http://www.w3.org/TR/media-frags/",
       "value": "xywh=10,10,100,100"
     },
     {
        "type": "SvgSelector",
        "value": "<svg:svg> ... </svg:svg>"
     }
  }
}
```

In the W3C annotation model: https://www.w3.org/TR/annotation-model/ it says:

"There MAY be 0 or more selector relationships associated with a Specific Resource. Multiple Selectors SHOULD select the same content, however some Selectors will not have the same precision as others. Consuming user agents MUST pick one of the described segments, if they are different. "

And looking into the historical discussion it looks like it was meant for our use case: https://github.com/w3c/web-annotation/issues/207

**Comment by robcast** [comment]
I created #21 for the alternate selectors issue.

**Comment by robcast** [comment]
@glenrobson I just looked at the WebAnno spec and I found `partOf` only on the `AnnotationPage`

https://www.w3.org/TR/annotation-model/#annotation-collection

Should we limit it to AnnotationPage? I agree that according to the spec an AnnotationPage can contain annotations on multiple targets but I think that in the IIIF annotation case we would only have annotations on one canvas.

Would the resource `scope` be a solution for the single annotation?

https://www.w3.org/TR/annotation-model/#scope-of-a-resource

```
{
  "@context": [
    "http://www.w3.org/ns/anno.jsonld",
    "http://iiif.io/api/presentation/3/context.json"
  ],
  "id": "http://example.org/anno1",
  "type": "Annotation",
  "motivation": "supplementing", 
  "body": {
        language: 'en',
        type: 'TextualBody',
        value: "annotation",
  },
  "target": {
    "type": "SpecificResource",
    "source": {
          "id": "http://example.org/manifest/1/canvas/1",
          "type": "Canvas",
          "label": { "en": [ "Page 1" ] } },
          "scope":  {
                   "id": ""http://example.org/manifest/1.json",
                   "type": "Manifest",
                   "label": { "en": [ "Manifest title" ] } }
             }
    }
    "selector": {
       "type": "FragmentSelector",
       "conformsTo": "http://www.w3.org/TR/media-frags/",
       "value": "xywh=10,10,100,100"
     }
  }
}
```

(The spec seems a bit vague if the "Relation" can be extended to an object)

**Comment by glenrobson** [comment]
Because the `partof` is in the canvas it falls into the IIIF spec rather than the annotation spec. It says here:

https://iiif.io/api/presentation/3.0/#partof

 that canvases can point to the manifest they are part of. So I think my example above is OK. As Rob mentions in slack the `source` can be any resource and in this case we are asserting its a canvas (hence the iiif context at the start of the annotation) and as a canvas type is defined by IIIF we can follow those rules.  

Does that answer your concern?

**Comment by robcast** [comment]
@glenrobson treating the source as a canvas makes sense, thanks for explaining!

I just wanted to make sure that our data is as correct as possible when it is set in stone, or, code that's going to be used a lot :-)

**Comment by robcast** [comment]
I started to implement loading the information in the SAS adapter but then I wasn't sure: do we really want to load and keep the `partOf` information or do we just generate the `partOf` based on the information in Mirador?

Is there a case where Mirador loads an annotation but it does not know its manifest?
