### ISSUE TITLE
annotation target should use "source" instead of "id" for the canvas uri when it has a "selector"

### ISSUE THREAD

**Issue by robcast** [ProjectMirador/mirador-annotations#25]
The current annotation model uses the target's `id` property for the canvas uri when the target has a selector.

According to the WebAnno spec the target is a `SpecificResource` when it has a `selector` and the resource uri should go into the `source` property (the `id` is of the SpecificResource object itself).

This concerns `WebAnnotation.js` and possible some adapters.

**Comment by robcast** [comment]
The last change in Mirador to accept extended target sources 

https://github.com/ProjectMirador/mirador/blob/982cd2c0b4e44a67201770e93e695af9bf6812c2/src/lib/AnnotationItem.js#L32

should also be amended to accept `target.source` without `target.source.id`. 

Should we keep `target.id` for backward-compatibility?

**Comment by mejackreed** [comment]
I'm not following exactly here. What is the change you would propose there? I thought we were targeting something like this: https://github.com/ProjectMirador/mirador-annotations/issues/20#issuecomment-665531532

**Comment by robcast** [comment]
`target.source.id` is fine in case we `source` is an object with additional information like `partOf`.

If we don't need that information `target.source` should be the URI that is currently in `target.id`.

**Comment by robcast** [comment]
I guess https://github.com/ProjectMirador/mirador/blob/982cd2c0b4e44a67201770e93e695af9bf6812c2/src/lib/AnnotationItem.js#L32

should become 
```Javascript
return (target.source && target.source.id) || target.source || target.id;
```
