### ISSUE TITLE
Add "Create new annotation" details

### ISSUE THREAD

**Issue by ggeisler** [ProjectMirador/mirador-annotations#4]
The details below enhance the current behavior of this plugin and sort of depend on the Annotations header menu pattern established in https://github.com/ProjectMirador/mirador/issues/3019 and https://github.com/ProjectMirador/mirador/issues/2946#issuecomment-627518655

## Create new annotation icon
<img width="427" alt="Screen Shot 2020-05-13 at 9 24 19 AM" src="https://user-images.githubusercontent.com/101482/81839436-5b245a80-94fc-11ea-86d8-3916a73d548b.png">

- [x] The icon is `add_box` at https://material.io/resources/icons/?search=create&icon=add_box&style=sharp

- [x] The tooltip should read `Create new annotation`:

<img width="397" alt="Screen Shot 2020-05-14 at 12 16 44 PM" src="https://user-images.githubusercontent.com/101482/81976061-d52c1080-95dc-11ea-9ce6-aa7efe0aafec.png">

## New annotation companion window
- [x] When the user selects the Create new annotation icon, a right-side companion window is opened:

<img width="899" alt="Screen Shot 2020-05-14 at 12 56 44 PM" src="https://user-images.githubusercontent.com/101482/81979989-b3ce2300-95e2-11ea-8fc5-304c695f84d1.png">

### B: Target, Style, and Content sections
There are three labeled toolbar/menubars. 

- [x] For the typography of the "Target," "Style," and "Content" labels, let's try [OVERLINE](https://github.com/ProjectMirador/mirador/issues/2093) first and see if that works. If it's too small we could try Subtitle2. 

- [x] The icons shown in the mockup are smaller than what they should be when implemented. We should size them the same as the other icons in the UI. This might cause a horizontal space problem for the Content menu; I wonder if there is an MUI/React pattern for horizontal scrolling that we could use here? We might also consider making the default width of the Add Annotation companion window a bit wider?

- The icons are intended to provide the same functionality as in Mirador 2, so I won't detail anything about those, with the one exception described in the next section. From discussion with @mejackreed I think the basic interaction pattern with creating a target, etc. is already in place and/or known.

### D: Annotation content textarea
This is a [multiline text input](https://material-ui.com/components/text-fields/#multiline), which initially displays a few lines and expands if the text exceeds the visible space:

<img width="312" alt="Screen Shot 2020-05-14 at 1 10 03 PM" src="https://user-images.githubusercontent.com/101482/81980882-458a6000-95e4-11ea-88bb-b2c7d9d9c130.png">

- [ ] I don't think we need a placeholder value but ideally it would resemble the outlined version of this component. Also, the label should be "Content", which we are already displaying above the toolbar. Can we use that as the field label for the multiline text input?

### E: Cancel and Save buttons
Selecting Cancel discards everything the user has done and closes the New annotation window.

Selecting Save:

- [x] Creates a new annotation with all of the relevant current target, style, content, and motivation selections, appended to the bottom of the annotationpage.

- [x] Refreshes the Annotation sidebar, if it is open, so that the newly created annotation is present on it and the annotation count message is updated.

- [ ] If necessary, scrolls the Annotation sidebar as necessary to ensure the saved annotation is visible. The annotation should be highlighted as if the user had selected that annotation; selected annotation gray background and selected annotation yellow region target highlighting:

<img width="902" alt="Screen Shot 2020-05-14 at 12 17 59 PM" src="https://user-images.githubusercontent.com/101482/81976418-5a172a00-95dd-11ea-8b44-973c241e4dc0.png">

(Split to #12)

### Responsive considerations
See #5 for how the window elements should adjust when the New annotation window is moved to horizontal mode.

**Comment by cbeer** [comment]
Outstanding todos split out to new tickets.

**Comment by Selphie** [comment]
Sorry if I got something wrong - is there already an implementation of the "content" part in the annotation section, i.e. that users are able to add attachements to an annotation?
(see screenshot https://user-images.githubusercontent.com/101482/81979989-b3ce2300-95e2-11ea-8fc5-304c695f84d1.png)

**Comment by geourjoa** [comment]
Hello @Selphie @ggeisler ,

I just discovered this issue. On my side in MAE : https://github.com/TETRAS-IIIF/mirador-annotation-editor I have implement quite close UI.

<img width="369" height="858" alt="Image" src="https://github.com/user-attachments/assets/8528fa08-8ec8-4a34-9722-ce5026d45c9e" />

I will be interested to know more about your UI work and see what can be done in MAE.
